// <auto-generated />
using System;
using FruitStockerAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FruitStockerAPI.Migrations
{
    [DbContext(typeof(FruitStockerContext))]
    [Migration("20191022113233_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("FruitStocker.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("FruitStocker.Model.FruitLot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<double>("QuantityLeft");

                    b.HasKey("Id");

                    b.ToTable("FruitLots");
                });

            modelBuilder.Entity("FruitStocker.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClientId");

                    b.Property<int?>("FruitsId");

                    b.Property<double>("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("FruitsId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FruitStocker.Model.Order", b =>
                {
                    b.HasOne("FruitStocker.Model.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId");

                    b.HasOne("FruitStocker.Model.FruitLot", "Fruits")
                        .WithMany()
                        .HasForeignKey("FruitsId");
                });
#pragma warning restore 612, 618
        }
    }
}
